#server.port=8080
#server.servlet.context-path=/api
server.port=8444
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store=file:D:/keystore.p12
#server.ssl.key-store-password=password123
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=myapp


springdoc.swagger-ui.path=/swagger-ui.html
